language: php
php:
  - 5.5
  - 5.4

before_script:
  - mysql -e 'create database dabl_test;'
  - psql -c 'create database dabl_test;' -U postgres
script:
  - phpunit --configuration tests/phpunit.xml tests/
